# Generated by Django 6.0.7 on 2026-08-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulletIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referee',
        ),
    ]
