# Generated by Django 6.0.7 on 2026-08-07 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gozlemci',
            name='ad_soyad',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='bolge',
            field=models.CharField(choices=[('ANA', 'Anadolu'), ('AV1', 'Avrupa-1'), ('AV2', 'Avrupa-2')], max_length=16, verbose_name='Bolge'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='eposta',
            field=models.EmailField(max_length=100, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Fotograf'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='gorev',
            field=models.CharField(choices=[('Hakem', 'Hakem'), ('Gözlemci', 'Gözlemci')], max_length=12, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='lisans_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lisans No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='meslek',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='tckn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{6}$')], verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='telefon_cep',
            field=models.CharField(max_length=24, verbose_name='Cep No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='telefon_dahili',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Dahili Telefon No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='telefon_ev',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Ev Telefon No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='telefon_is',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='İş Telefon No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='ad_soyad',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='bolge',
            field=models.CharField(choices=[('ANA', 'Anadolu'), ('AV1', 'Avrupa-1'), ('AV2', 'Avrupa-2')], max_length=16, verbose_name='Bolge'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='eposta',
            field=models.EmailField(max_length=100, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Fotograf'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='gorev',
            field=models.CharField(choices=[('Hakem', 'Hakem'), ('Gözlemci', 'Gözlemci')], max_length=12, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='lisans_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lisans No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='meslek',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='tckn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{6}$')], verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='telefon_cep',
            field=models.CharField(max_length=24, verbose_name='Cep No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='telefon_dahili',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Dahili Telefon No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='telefon_ev',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Ev Telefon No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='telefon_is',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='İş Telefon No'),
        ),
    ]
