# Generated by Django 6.0.7 on 2026-08-12 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_gozlemci_ad_soyad_alter_gozlemci_bolge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gozlemci',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hakem',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='klasman',
            field=models.CharField(choices=[('IL', 'İl Gözlemcisi'), ('BG', 'BG'), ('KG', 'KG'), ('ÜKG', 'ÜKG')], default=0, verbose_name='Klaman'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='tckn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{11}$')], verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='tckn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{11}$')], verbose_name='Kimlik No'),
        ),
    ]
