# Generated by Django 6.0.7 on 2026-08-12 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_gozlemci_user_hakem_user_alter_gozlemci_klasman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gozlemci',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='aile_sira_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aile Sıra No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='anne_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anne Adı'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='askerlik_durumu',
            field=models.CharField(blank=True, choices=[('TECILLI', 'Tecilli'), ('YAPTI', 'Yaptı'), ('MUAF', 'Muaf')], max_length=20, null=True, verbose_name='Askerlik Durumu'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='baba_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baba Adı'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='banka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banka'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='bolge',
            field=models.CharField(blank=True, choices=[('ANA', 'Anadolu'), ('AV1', 'Avrupa-1'), ('AV2', 'Avrupa-2')], max_length=16, null=True, verbose_name='Bolge'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='cilt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cilt No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('ERKEK', 'Erkek'), ('KADIN', 'Kadın')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='egitim_seviyesi',
            field=models.CharField(blank=True, choices=[('ILKOKUL', 'İlkokul'), ('ORTAOKUL', 'Ortaokul'), ('LISE', 'Lise'), ('ONLISANS', 'Önlisans'), ('LISANS', 'Lisans'), ('YUKSEK_LISANS', 'Yüksek Lisans'), ('DOKTORA', 'Doktora')], max_length=20, null=True, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='eposta',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='gorev',
            field=models.CharField(blank=True, choices=[('Hakem', 'Hakem'), ('Gözlemci', 'Gözlemci')], max_length=12, null=True, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='hesap_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hesap No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='ilce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='kan_grubu',
            field=models.CharField(blank=True, choices=[('0_RH_POS', '0 RH+'), ('0_RH_NEG', '0 RH-'), ('A_RH_POS', 'A RH+'), ('A_RH_NEG', 'A RH-'), ('B_RH_POS', 'B RH+'), ('B_RH_NEG', 'B RH-'), ('AB_RH_POS', 'AB RH+'), ('AB_RH_NEG', 'AB RH-')], max_length=10, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='klasman',
            field=models.CharField(choices=[('IL', 'İl Gözlemcisi'), ('BG', 'BG'), ('KG', 'KG'), ('ÜKG', 'ÜKG')], default=0, verbose_name='Klasman'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='mahalle_koy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mahalle/Köy'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='medeni_hal',
            field=models.CharField(blank=True, choices=[('BEKAR', 'Bekar'), ('EVLI', 'Evli')], max_length=10, null=True, verbose_name='Medeni Hal'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='mezun_oldugu_okul',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mezun Olduğu Okul Adı'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='mezuniyet_yili',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mezuniyet Yılı'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='nufus_il',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İl (Nüfus)'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='nufus_ilce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe (Nüfus)'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='semt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Semt'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='sira_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sıra No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='sube_kodu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Şube Kodu'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{11}$')], verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='gozlemci',
            name='telefon_cep',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Cep No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='aile_sira_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aile Sıra No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='anne_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anne Adı'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='askerlik_durumu',
            field=models.CharField(blank=True, choices=[('TECILLI', 'Tecilli'), ('YAPTI', 'Yaptı'), ('MUAF', 'Muaf')], max_length=20, null=True, verbose_name='Askerlik Durumu'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='baba_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baba Adı'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='banka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banka'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='bolge',
            field=models.CharField(blank=True, choices=[('ANA', 'Anadolu'), ('AV1', 'Avrupa-1'), ('AV2', 'Avrupa-2')], max_length=16, null=True, verbose_name='Bolge'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='cilt_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cilt No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('ERKEK', 'Erkek'), ('KADIN', 'Kadın')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='egitim_seviyesi',
            field=models.CharField(blank=True, choices=[('ILKOKUL', 'İlkokul'), ('ORTAOKUL', 'Ortaokul'), ('LISE', 'Lise'), ('ONLISANS', 'Önlisans'), ('LISANS', 'Lisans'), ('YUKSEK_LISANS', 'Yüksek Lisans'), ('DOKTORA', 'Doktora')], max_length=20, null=True, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='eposta',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='gorev',
            field=models.CharField(blank=True, choices=[('Hakem', 'Hakem'), ('Gözlemci', 'Gözlemci')], max_length=12, null=True, verbose_name='Gorev'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='hesap_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hesap No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='ilce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='kan_grubu',
            field=models.CharField(blank=True, choices=[('0_RH_POS', '0 RH+'), ('0_RH_NEG', '0 RH-'), ('A_RH_POS', 'A RH+'), ('A_RH_NEG', 'A RH-'), ('B_RH_POS', 'B RH+'), ('B_RH_NEG', 'B RH-'), ('AB_RH_POS', 'AB RH+'), ('AB_RH_NEG', 'AB RH-')], max_length=10, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='mahalle_koy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mahalle/Köy'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='medeni_hal',
            field=models.CharField(blank=True, choices=[('BEKAR', 'Bekar'), ('EVLI', 'Evli')], max_length=10, null=True, verbose_name='Medeni Hal'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='mezun_oldugu_okul',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mezun Olduğu Okul Adı'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='mezuniyet_yili',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mezuniyet Yılı'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='nufus_il',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İl (Nüfus)'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='nufus_ilce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe (Nüfus)'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='semt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Semt'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='sira_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sıra No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='sube_kodu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Şube Kodu'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Bu alan tam olarak 11 haneli bir sayı olmalıdır.', regex='^\\d{11}$')], verbose_name='Kimlik No'),
        ),
        migrations.AlterField(
            model_name='hakem',
            name='telefon_cep',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Cep No'),
        ),
    ]
